on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            
          - os: ubuntu-latest
            target: i686-unknown-linux-musl

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            
          - os: windows-latest
            target: i686-pc-windows-msvc

          - os: macos-latest
            target: x86_64-apple-darwin
          
          - os: macos-latest
            target: i686-apple-darwin

    steps:
    - name: Disable git eol translation
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install target
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --target=${{ matrix.target }}
